import { useState } from "react";
import Section from "../components/ui/Section.jsx";
import Container from "../components/ui/Container.jsx";
import Button from "../components/ui/Button.jsx";
import { supabase, isSupabaseConfigured } from "../lib/supabase.js";

const directions=["Build From Scratch","Revamp My Community","Improve Specific Systems","Help Me Find My Community Direction"];
const communityTypes=["Streamer Community","Creator Community","Gaming Community","Business Community","Online Community","Other"];
const vibes=["","The Gaming Hub","The Cyber World","The Elite Club","The Racing Garage","Other"];
const approaches=["","I Want To Discuss The Complete Community","I Prefer Building In Phases","I Need Help With A Smaller Project","I Am Not Sure Yet"];

function StartYourProject(){
 const [form,setForm]=useState({name:"",email:"",project_directions:[],community_type:"",project_details:"",community_direction:"",budget_approach:""});
 const [errors,setErrors]=useState({}); const [state,setState]=useState("idle"); const [message,setMessage]=useState("");
 const update=(key,val)=>setForm(f=>({...f,[key]:val}));
 const toggle=d=>update("project_directions",form.project_directions.includes(d)?form.project_directions.filter(x=>x!==d):[...form.project_directions,d]);
 function validate(){const e={}; if(!form.name.trim())e.name="Please enter your name."; if(!/^\S+@\S+\.\S+$/.test(form.email))e.email="Please enter a valid email address."; if(!form.project_directions.length)e.project_directions="Choose at least one direction."; if(!form.community_type)e.community_type="Choose what you are working on."; if(form.project_details.trim().length<20)e.project_details="Please tell us a little more about your project."; setErrors(e); return !Object.keys(e).length;}
 async function submit(e){e.preventDefault();setMessage("");if(!validate())return;if(!isSupabaseConfigured){setState("error");setMessage("The project inquiry system is not configured yet.");return;}setState("submitting");const {error}=await supabase.from("project_inquiries").insert([{...form,project_directions:form.project_directions,status:"new"}]);if(error){setState("error");setMessage("We could not submit your inquiry right now. Please try again.");return;}setState("success");setMessage("Thank you for sharing your project direction. Your inquiry has been received successfully. We now have the information needed to understand what you are looking to build or improve.");setForm({name:"",email:"",project_directions:[],community_type:"",project_details:"",community_direction:"",budget_approach:""});}
 const input="mt-2 w-full rounded-xl border border-border bg-surface px-4 py-3 text-ink placeholder:text-ink-muted focus:border-cyan focus:outline-none";
 return <main className="bg-brand-field pb-20"><Section className="pt-20"><Container><div className="max-w-4xl"><p className="text-sm font-semibold tracking-[.2em] text-cyan">SHALOMHEGA NETWORKS</p><h1 className="mt-5 text-4xl font-bold sm:text-6xl">LET&apos;S TALK ABOUT YOUR COMMUNITY</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-ink-muted">Whether you want to build something completely new, improve an existing community, or figure out where to start, the first step is understanding your direction.</p><p className="mt-8 font-semibold tracking-[.16em] text-purple">EVERY COMMUNITY STARTS WITH A CONVERSATION</p></div></Container></Section>
 <Section><Container><form onSubmit={submit} className="grid gap-8 rounded-3xl border border-border bg-surface/80 p-6 shadow-2xl shadow-purple/5 md:p-10">
 <div><h2 className="text-2xl font-bold">WHAT DO YOU NEED HELP WITH?</h2><p className="mt-2 text-ink-muted">Choose one or more directions that match your project.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{directions.map(d=><button type="button" key={d} onClick={()=>toggle(d)} className={`rounded-2xl border p-5 text-left transition ${form.project_directions.includes(d)?"border-cyan bg-cyan/10":"border-border bg-background hover:border-purple"}`}><span className="font-semibold">{d.toUpperCase()}</span></button>)}</div>{errors.project_directions&&<p className="mt-2 text-sm text-red-300">{errors.project_directions}</p>}</div>
 <div className="grid gap-5 md:grid-cols-2"><label>NAME<input className={input} value={form.name} onChange={e=>update("name",e.target.value)} placeholder="Your name"/>{errors.name&&<span className="text-sm text-red-300">{errors.name}</span>}</label><label>EMAIL<input className={input} value={form.email} onChange={e=>update("email",e.target.value)} placeholder="you@example.com"/>{errors.email&&<span className="text-sm text-red-300">{errors.email}</span>}</label></div>
 <label>WHAT ARE YOU WORKING ON?<select className={input} value={form.community_type} onChange={e=>update("community_type",e.target.value)}><option value="">Select one</option>{communityTypes.map(x=><option key={x}>{x}</option>)}</select>{errors.community_type&&<span className="text-sm text-red-300">{errors.community_type}</span>}</label>
 <label>TELL US ABOUT YOUR PROJECT<textarea className={`${input} min-h-44`} value={form.project_details} onChange={e=>update("project_details",e.target.value)} placeholder="Tell us what you currently have, what you want to improve, what you want to build, and where you want your community to go."/>{errors.project_details&&<span className="text-sm text-red-300">{errors.project_details}</span>}</label>
 <div className="grid gap-5 md:grid-cols-2"><label>COMMUNITY DIRECTION, OPTIONAL<select className={input} value={form.community_direction} onChange={e=>update("community_direction",e.target.value)}>{vibes.map(x=><option key={x} value={x}>{x||"No preference yet"}</option>)}</select></label><label>BUDGET OR PROJECT APPROACH, OPTIONAL<select className={input} value={form.budget_approach} onChange={e=>update("budget_approach",e.target.value)}>{approaches.map(x=><option key={x} value={x}>{x||"Select an approach"}</option>)}</select></label></div>
 {message&&<div className={`rounded-2xl border p-5 ${state==="success"?"border-cyan/40 bg-cyan/10":"border-red-400/40 bg-red-400/10"}`}>{message}</div>}
 <div><Button type="submit" size="md" disabled={state==="submitting"}>{state==="submitting"?"SENDING...":"START THE CONVERSATION"}</Button></div>
 </form></Container></Section>
 <Section><Container><div className="grid gap-5 md:grid-cols-2"><div className="rounded-2xl border border-border bg-surface p-6"><p className="text-xs tracking-widest text-cyan">EMAIL</p><p className="mt-2 text-lg">shalomcostar@gmail.com</p></div><div className="rounded-2xl border border-border bg-surface p-6"><p className="text-xs tracking-widest text-cyan">DISCORD</p><p className="mt-2 text-lg">shalom_x2</p></div></div></Container></Section></main>}
export default StartYourProject;
