import { useState } from "react";
import { Navigate, useNavigate } from "react-router-dom";
import Button from "../../components/ui/Button.jsx";
import { supabase, isSupabaseConfigured } from "../../lib/supabase.js";

function AdminLogin(){const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState("");const nav=useNavigate();
async function submit(e){e.preventDefault();if(!isSupabaseConfigured){setError("Supabase is not configured yet.");return;}setLoading(true);setError("");const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error){setError("We could not sign you in. Check your credentials and try again.");setLoading(false);return;}const {data:admin}=await supabase.from("admin_users").select("user_id").eq("user_id",data.user.id).maybeSingle();if(!admin){await supabase.auth.signOut();setError("This account is not authorized to access the administration area.");setLoading(false);return;}nav("/admin/dashboard");}
return <main className="min-h-screen bg-brand-field px-5 py-12"><div className="mx-auto max-w-md rounded-3xl border border-border bg-surface p-7 sm:p-9"><p className="text-cyan text-xs font-semibold tracking-[0.22em]">SHALOMHEGA NETWORKS</p><h1 className="mt-4 text-3xl font-bold">ADMIN ACCESS</h1><p className="mt-3 text-sm leading-6 text-ink-muted">Secure access for authorized review management.</p>{error&&<div className="mt-6 rounded-xl border border-red-400/30 bg-red-400/10 p-3 text-sm">{error}</div>}<form onSubmit={submit} className="mt-7 grid gap-5"><label className="grid gap-2 text-sm">EMAIL<input type="email" value={email} onChange={e=>setEmail(e.target.value)} className="rounded-xl border border-border bg-background px-4 py-3 outline-none focus:border-cyan" required/></label><label className="grid gap-2 text-sm">PASSWORD<input type="password" value={password} onChange={e=>setPassword(e.target.value)} className="rounded-xl border border-border bg-background px-4 py-3 outline-none focus:border-cyan" required/></label><Button type="submit" className="w-full py-3.5" disabled={loading}>{loading?"SIGNING IN...":"SIGN IN"}</Button></form></div></main>}
export default AdminLogin;
